#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes
#+Startup: showeverything
#+Options: toc:2

* Table Of Contents                                                     :toc:
- [[#core-setup-and-performance][Core setup and performance]]
  - [[#startup-performance][Startup Performance]]
  - [[#auto-tangle-configuration-file][Auto-tangle Configuration file]]
  - [[#show-startup-time][Show startup time]]
  - [[#use-package][Use Package]]
  - [[#setting-package-repositories][Setting package repositories]]
  - [[#package-quickstart][Package quickstart]]
  - [[#good-defaults][Good Defaults]]
- [[#important-to-load-first][Important to load first]]
  - [[#traditional-emacs-style-keybindings][Traditional Emacs-style Keybindings]]
- [[#appearance][Appearance]]
  - [[#set-theme][Set Theme]]
  - [[#ultra-scroll][Ultra scroll]]
  - [[#transparency][Transparency]]
  - [[#fonts][Fonts]]
  - [[#modeline][Modeline]]
  - [[#nerd-icons][Nerd Icons]]
- [[#development][Development]]
  - [[#add-binaries-to-path][Add binaries to path]]
  - [[#projectile][Projectile]]
  - [[#eglot][Eglot]]
  - [[#sideline-flymake][Sideline-flymake]]
  - [[#yasnippet][Yasnippet]]
  - [[#envrc][Envrc]]
  - [[#treesitter][Treesitter]]
  - [[#language-modes][Language modes]]
  - [[#ai][AI]]
  - [[#terminal][Terminal]]
- [[#version-control][Version control]]
  - [[#git][Git]]
- [[#completion][Completion]]
  - [[#corfu][Corfu]]
  - [[#cape][Cape]]
  - [[#orderless][Orderless]]
  - [[#vertico-and-marginalia][Vertico and Marginalia]]
  - [[#consult][Consult]]
  - [[#embark][Embark]]
  - [[#wgrep][Wgrep]]
  - [[#helpful][Helpful]]
  - [[#treemacs][Treemacs]]
  - [[#diminish][Diminish]]
  - [[#rainbow-delimiters][Rainbow Delimiters]]
  - [[#which-key][Which-Key]]
  - [[#ws-butler][Ws-butler]]
- [[#runtime-performance][Runtime Performance]]

* Core setup and performance
** Startup Performance
Make startup faster by reducing the frequency of garbage collection. This will be set back when startup finishes.
#+begin_src emacs-lisp
  ;; The default is 800 kilobytes. Measured in bytes.
  (setq gc-cons-threshold (* 50 1000 1000))
#+end_src

** Auto-tangle Configuration file
Auto-Tangle Org configuration file for better startup times.
If you want to use this don't forget to add this to the top of the org document (#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes)

*Remember*, if this code can't be loaded (errors before this code), the init.el file won't update on change!
To fix this, you need to find this file (C-x C-f), fix the error and press C-c C-v t to tangle it manually.

This snippet adds a hook to org-mode buffers so that start/org-babel-tangle-config gets executed each time such a buffer gets saved.
This function checks to see if the file being saved is the Emacs.org file you’re looking at right now, and if so,
automatically exports the configuration here to the associated output files.
#+begin_src emacs-lisp
  (defun start/remove-org-babel-results ()
    "Remove all #+RESULTS blocks in the current org buffer."
    (interactive)
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward "^#\\+RESULTS:.*\n" nil t)
        (let ((results-begin (match-beginning 0)))
          ;; Find the end of the results block
          (forward-line 1)
          (let ((results-end (point)))
            ;; Check if there's a drawer or example block
            (cond
             ;; Handle #+begin_example ... #+end_example blocks
             ((looking-at "^#\\+begin_example")
              (when (re-search-forward "^#\\+end_example" nil t)
                (forward-line 1)
                (setq results-end (point))))
             ;; Handle : prefixed results
             ((looking-at "^:")
              (while (and (not (eobp)) (looking-at "^:"))
                (forward-line 1))
              (setq results-end (point)))
             ;; Handle single line results
             ((not (looking-at "^$\\|^#\\|^\\*"))
              (forward-line 1)
              (setq results-end (point))))
            ;; Also remove any trailing blank line after results
            (when (looking-at "^$")
              (forward-line 1)
              (setq results-end (point)))
            ;; Delete the results block
            (delete-region results-begin results-end))))))

  (defun start/org-babel-tangle-config ()
    "Automatically tangle our init.org config file and refresh package-quickstart when we save it."
    (interactive)
    (when (and (buffer-file-name)  ;; This handles nil buffer-file-name
               ;; Use file-truename to handle simlinks (eg. when using GNU stow)
               ;; Use equal instead of string-equal as file-truename returns list-like structure
               (equal (file-truename (file-name-directory (buffer-file-name)))
                      (file-truename (expand-file-name user-emacs-directory))))
      ;; Remove results blocks before tangling
      (start/remove-org-babel-results)
      (let ((org-confirm-babel-evaluate nil)
            (warning-minimum-level :error)      ;; Suppress warnings, they are annoying
            (byte-compile-warnings nil))        ;; Disable byte-compile warnings
        (org-babel-tangle)
        (package-quickstart-refresh))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'start/org-babel-tangle-config)))
#+end_src

** Show startup time
#+begin_src emacs-lisp
  (defun start/display-startup-time ()
    (message "Emacs loaded in %s with %d garbage collections."
             (format "%.2f seconds"
                     (float-time
  										(time-subtract after-init-time before-init-time)))
             gcs-done))

  (add-hook 'emacs-startup-hook #'start/display-startup-time)
#+end_src

** Use Package
A macro that allows you to isolate package configuration in your .emacs file in a 
way that is both performance-oriented and, well, tidy. We use it because it makes 
package configuration really easy.

With Emacs 29 use-package is now built-in.

This code eliminates the need to type :ensure t for each package download. 
Instead, you’ll only need to use :ensure nil when you want to explicitly prevent a 
package from being downloaded.
#+begin_src emacs-lisp
  (require 'use-package-ensure) ;; Load use-package-always-ensure
  (setq use-package-always-ensure t) ;; Always ensures that a package is installed

#+end_src


** Setting package repositories
Like Linux distributions, Emacs uses repositories to manage its packages.

#+begin_src emacs-lisp
  (setq package-archives '(("melpa" . "https://melpa.org/packages/") ;; Sets default package repositories
                           ("org" . "https://orgmode.org/elpa/")
                           ("elpa" . "https://elpa.gnu.org/packages/")
                           ("nongnu" . "https://elpa.nongnu.org/nongnu/")))
#+end_src


** Package quickstart

Improves startup times by allowing Emacs to precompute and generate a single, 
large autoload file. Instead of re-computing them on every startup.

The larger your configuration, the more it will be felt at startup.

However, if you enable this, you’ll need to manually run the package-quickstart-refresh 
command whenever your package activations change, such as when you modify the package-load-list 
value. We put it inside Auto-tangle hook so when we save this file it runs it automatically.

As I tested, it makes startup about 0.1 seconds faster. Avg:

Off: 0.66 sec
On: 0.59 sec

Package quickstart only works with package.el. If you plan to use a different
package manager, remember to remove this section and the package-quickstart-refresh 
line in the Auto-tangle hook.

#+begin_src emacs-lisp
  (setq package-quickstart t) ;; For blazingly fast startup times, this line makes startup miles faster

  ;; Refresh the quickstart file after any package install/delete/upgrade so its
  ;; autoloads don't go stale when upgrading outside of saving init.org.
  (dolist (fn '(package-install
                package-delete
                package-upgrade
                package-upgrade-all))
    (when (fboundp fn)
      (advice-add fn :after (lambda (&rest _) (package-quickstart-refresh)))))
#+end_src

** Good Defaults
#+begin_src emacs-lisp
  (use-package emacs
  	:custom
  	(menu-bar-mode nil)         ;; Disable the menu bar
  	(scroll-bar-mode nil)       ;; Disable the scroll bar
  	(tool-bar-mode nil)         ;; Disable the tool bar
  	(inhibit-startup-screen t)  ;; Disable welcome screen

    (delete-selection-mode t)   ;; Select text and delete it by typing.
    (electric-indent-mode nil)  ;; Turn off the weird indenting that Emacs does by default.
    (electric-pair-mode t)      ;; Turns on automatic parens pairing

    (blink-cursor-mode nil)     ;; Don't blink cursor
    (global-auto-revert-mode t) ;; Automatically reload file and show changes if the file has changed

    (recentf-mode t) ;; Enable recent file mode (needed by consult-recent-file)

    (display-line-numbers-width 4)          ;; Fixed width for line numbers (prevents horizontal shift)
    (global-display-line-numbers-mode t)    ;; Display line numbers (absolute by default)
  	(column-number-mode t)                  ;; Display column in mode line

    (mouse-wheel-progressive-speed nil) ;; Disable progressive speed when scrolling

  	(use-short-answers t)  ;; Use short answers (y instead of yes)

  	(indent-tabs-mode nil)
    (tab-width 2)

    (make-backup-files nil) ;; Stop creating ~ backup files
    (auto-save-default nil) ;; Stop creating # auto save files
    :hook
    (prog-mode . (lambda () (hs-minor-mode t))) ;; Enable folding hide/show globally
    :config
    ;; Move customization variables to a separate file and load it, avoid filling up init.el with unnecessary variables
    (setq custom-file (locate-user-emacs-file "custom-vars.el"))
    (load custom-file 'noerror 'nomessage)
    :bind (
           ([escape] . keyboard-escape-quit) ;; Makes Escape quit prompts (Minibuffer Escape)
           ;; You can use the bindings C-+ C-- for zooming in/out. 
  				 ;; You can also use CTRL plus the mouse wheel for zooming in/out.
           ("C-+" . text-scale-increase)
           ("C--" . text-scale-decrease)
           ("<C-wheel-up>" . text-scale-increase)
           ("<C-wheel-down>" . text-scale-decrease))

    )
#+end_src

* Important to load first

** Traditional Emacs-style Keybindings
Emacs follows conventions for organizing keybindings under standard prefixes.

Standard Emacs prefixes:
- C-x: File, buffer, window operations (built-in)
- C-c: User and mode-specific commands (reserved for users)
- C-h: Help system (built-in)
- M-s: Search operations (built-in)
- C-x p: Project commands (built-in, enhanced with consult-project-extra)

Custom prefixes defined below:
- C-c f: Find operations (files, projects, recent files)
- C-c s: Search operations (grep, line search, symbols)
- C-c b: Buffer operations (switch, kill, reload)
- C-c g: Git/Version control (magit commands)
- C-c e: Language/Eglot operations (LSP, diagnostics)
- C-c t: Toggle operations (line numbers, themes, modes)
- C-c p: Project operations (projectile-specific commands)

Other global bindings:
- C-.: embark-act (contextual actions on candidate/target)
- C-,: embark-dwim (act on thing at point)
- C-;: avy-goto-char-timer (jump to visible text)

#+begin_src emacs-lisp
  (use-package avy
    :bind ("C-;" . avy-goto-char-timer))
#+end_src

#+begin_src emacs-lisp
  (use-package general
    :config
    ;; C-c f prefix: Find operations (files, projects, etc.)
    (general-create-definer start/find-keys
      :prefix "C-c f")

    (start/find-keys
      "" '(:ignore t :wk "Find")
      "f" '(consult-find :wk "Find file (all, includes hidden)")
      "d" '(consult-fd :wk "Find file with fd (respects .gitignore)")
      "p" '(consult-project-extra-find :wk "Find in project (buffers/files/projects)")
      "o" '(consult-project-extra-find-other-window :wk "Find in project other window (buffers/files/projects)")
      "r" '(consult-recent-file :wk "Recent files")
      "l" '(consult-locate :wk "Locate file (system-wide)"))

    ;; C-c s prefix: Search operations (grep, line search, etc.)
    (general-create-definer start/search-keys
      :prefix "C-c s")

    (start/search-keys
      "" '(:ignore t :wk "Search")
      "s" '(consult-line :wk "Search line in buffer")
      "g" '(consult-ripgrep :wk "Ripgrep in project")
      "G" '(consult-git-grep :wk "Git grep in repository")
      "r" '(consult-grep :wk "Grep in directory")
      "i" '(consult-imenu :wk "Search symbols (Imenu)")
      "I" '(consult-imenu-multi :wk "Search symbols across buffers")
      "o" '(consult-outline :wk "Search outline headings")
      "m" '(consult-mark :wk "Jump to mark")
      "M" '(consult-global-mark :wk "Jump to global mark"))

    ;; Extend M-s (built-in search prefix) with consult commands
    ;; M-s is the traditional Emacs search prefix
    (general-define-key
     :keymaps 'search-map  ;; search-map is bound to M-s by default
     "r" '(consult-ripgrep :wk "Ripgrep")
     "l" '(consult-line :wk "Search line")
     "i" '(consult-imenu :wk "Imenu")
     "o" '(consult-outline :wk "Outline"))

    ;; C-c b prefix: Buffer operations
    (general-create-definer start/buffer-keys
      :prefix "C-c b")

    (start/buffer-keys
      "" '(:ignore t :wk "Buffers")
      "b" '(consult-buffer :wk "Switch buffer (all sources)")
      "p" '(consult-project-buffer :wk "Switch project buffer")
      "o" '(consult-buffer-other-window :wk "Switch buffer (other window)")
      "k" '(kill-current-buffer :wk "Kill current buffer")
      "K" '(kill-buffer :wk "Kill buffer (select)")
      "r" '(revert-buffer :wk "Reload buffer")
      "s" '(save-buffer :wk "Save buffer")
      "S" '(save-some-buffers :wk "Save modified buffers"))

    ;; C-c g prefix: Git/Version control operations
    (general-create-definer start/git-keys
      :prefix "C-c g")

    (start/git-keys
      "" '(:ignore t :wk "Git")
      "s" '(magit-status :wk "Magit status")
      "d" '(magit-diff :wk "Magit diff")
      "l" '(magit-log :wk "Magit log")
      "b" '(magit-blame :wk "Magit blame")
      "c" '(magit-commit :wk "Magit commit"))

    ;; C-c e prefix: Language/Eglot operations
    (general-create-definer start/eglot-keys
      :prefix "C-c e")

    (start/eglot-keys
      "" '(:ignore t :wk "Language/Eglot")
      "e" '(eglot-reconnect :wk "Eglot reconnect")
      "f" '(eglot-format :wk "Format buffer")
      "r" '(eglot-rename :wk "Rename symbol")
      "a" '(eglot-code-actions :wk "Code actions")
      "d" '(eldoc-doc-buffer :wk "Show documentation")
      "l" '(consult-flymake :wk "List diagnostics")
      "n" '(flymake-goto-next-error :wk "Next diagnostic")
      "p" '(flymake-goto-prev-error :wk "Previous diagnostic"))

    ;; C-c t prefix: Toggle operations
    (general-create-definer start/toggle-keys
      :prefix "C-c t")

    (start/toggle-keys
      "" '(:ignore t :wk "Toggle")
      "l" '(display-line-numbers-mode :wk "Line numbers")
      "w" '(visual-line-mode :wk "Visual line mode (wrap)")
      "t" '(consult-theme :wk "Switch theme")
      "f" '(toggle-frame-fullscreen :wk "Fullscreen"))

    ;; C-c p prefix: Project operations
    ;; Projectile handles project detection and switching; consult provides the
    ;; preview-rich finders. They're bridged via `consult-project-function' =
    ;; projectile-project-root, so consult commands honor projectile's projects.
    (general-create-definer start/project-keys
      :prefix "C-c p")

    (start/project-keys
      "" '(:ignore t :wk "Project")
      "p" '(projectile-switch-project :wk "Switch project")
      "f" '(consult-project-extra-find :wk "Find file (with preview)")
      "b" '(consult-project-buffer :wk "Switch buffer (with preview)")
      "d" '(projectile-find-dir :wk "Find directory")
      "c" '(projectile-compile-project :wk "Compile")
      "t" '(projectile-test-project :wk "Run tests")
      "r" '(projectile-run-project :wk "Run project")
      "k" '(projectile-kill-buffers :wk "Kill project buffers")
      "i" '(projectile-invalidate-cache :wk "Invalidate cache")
      "D" '(projectile-dired :wk "Dired at root"))

    ;; Additional useful global bindings
    (general-define-key
     "C-x b" '(consult-buffer :wk "Switch buffer")  ;; Replace default switch-to-buffer
     "C-x 4 b" '(consult-buffer-other-window :wk "Switch buffer other window")
     "M-y" '(consult-yank-from-kill-ring :wk "Yank from kill ring")  ;; Better than yank-pop
     "M-g i" '(consult-imenu :wk "Imenu")
     "M-g o" '(consult-outline :wk "Outline")
     "M-g m" '(consult-mark :wk "Jump to mark")
     "M-g M" '(consult-global-mark :wk "Jump to global mark"))
    )
#+end_src


* Appearance

** Set Theme
Use consult-theme to easily try out themes (*Epilepsy* Warning).
#+begin_src emacs-lisp
  (load-theme 'modus-vivendi-tinted t)
#+end_src

** Ultra scroll
#+begin_src emacs-lisp
  (use-package ultra-scroll
  	:init
  	(setq scroll-conservatively 101
  				scroll-margin 0)        ; important: scroll-margin>0 not yet supported
  	:config
  	(ultra-scroll-mode 1))
#+end_src 

** Transparency
With Emacs version 29, true transparency has been added.
#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(alpha-background . 95)) ;; For all new frames henceforth
#+end_src

** Fonts
*** Setting fonts
#+begin_src emacs-lisp
  (set-face-attribute 'default nil
                      :font "JetBrainsMono Nerd Font" ;; Set your favorite type of font or download JetBrains Mono
                      :height 120
                      :weight 'medium)
  ;; This sets the default font on all graphical frames created after restarting Emacs.
  ;; Does the same thing as 'set-face-attribute default' above, but emacsclient fonts
  ;; are not right unless I also add this method of setting the default font.

  (add-to-list 'default-frame-alist '(font . "JetBrainsMono Nerd Font")) ;; Set your favorite font
  (setq-default line-spacing 0.2)
#+end_src

** Modeline
Replace the default modeline with a prettier more useful.
#+begin_src emacs-lisp
  (use-package doom-modeline
    :init (doom-modeline-mode 1)
    :custom
    (doom-modeline-height 25)     ;; Sets modeline height
    (doom-modeline-bar-width 5))  ;; Sets right bar width
#+end_src

** Nerd Icons
For icons and more helpful UI.
This is an icon set that can be used with dired, ibuffer and other Emacs programs.

Don't forget to use nerd-icons-install-fonts.

We use Nerd icons because it has more, better icons and all-the-icons only supports GUI.
While nerd-icons supports both GUI and TUI.
#+begin_src emacs-lisp
  (use-package nerd-icons)

  (use-package nerd-icons-dired
    :hook (dired-mode . (lambda () (nerd-icons-dired-mode t))))

  (use-package nerd-icons-ibuffer
    :hook (ibuffer-mode . nerd-icons-ibuffer-mode))
#+end_src

* Development

** Add binaries to path
Add a path for custom binaries
#+begin_src emacs-lisp
  (add-to-list 'exec-path "~/.local/bin/")
  (add-to-list 'exec-path "~/dev/bin/")
#+end_src

** Projectile
Project interaction library for Emacs.
#+begin_src emacs-lisp
  (use-package projectile
    :init
    (projectile-mode)
  	:config
  	(add-hook 'project-find-functions #'project-projectile)
    :custom
    (projectile-run-use-comint-mode t) ;; Interactive run dialog when running projects inside emacs (like giving input)
    (projectile-switch-project-action #'projectile-find-file) ;; Drop into find-file on project switch
    (projectile-project-search-path '(("~/dev" . 2)))) ;; Search up to 2 subdirectory levels deep for projects
#+end_src

** Eglot
Language Server Protocol Support for Emacs. The built-in is now Eglot (with emacs 29).

Eglot is fast and minimal, but requires manual setup for LSP servers (downloading).
For more [[https://www.gnu.org/software/emacs/manual/html_mono/eglot.html][information how to use.]] One alternative to Eglot is Lsp-mode, check out the [[https://github.com/MiniApollo/kickstart.emacs/wiki][project wiki]] page for more information.

Eglot is easy to set up, but the only difficult part is downloading and setting up the lsp servers.
After that just add a hook with eglot-ensure to automatically start eglot for a given file type. And you are done.

As an example to use C, C++ you need to install clangd(or ccls) and uncomment the following lines. Now the language server will start automatically when opening any c,c++ file.

A harder example is Lua. Download the lua-language-server from their git repository, make the lua-language-server file executable at lua-language-server/bin.
Uncomment the following lines and change the path to the language server executable. Now the language server will work.
Or add the lua-language-server executable to your path.

If you can use a package manager just install the lsp server and add a hook.
#+begin_src emacs-lisp
  (use-package eglot
    :ensure nil
    :hook
    (python-ts-mode . eglot-ensure)
    :config
    (add-to-list 'eglot-server-programs
                 '((python-ts-mode python-mode) . ("pyright-langserver"))))

  (add-hook 'python-ts-mode-hook
            (lambda () (add-hook 'before-save-hook #'eglot-format nil t)))

  ;; Configure Elixir LSP only on Linux
  (when (eq system-type 'gnu/linux)
    (with-eval-after-load 'eglot
      (setf (alist-get '(elixir-mode elixir-ts-mode heex-ts-mode)
                       eglot-server-programs
                       nil nil #'equal)
            (eglot-alternatives
             '(("expert_linux_amd64" "--stdio") "start_lexical.sh")))))
#+end_src

** Sideline-flymake

#+begin_src emacs-lisp
  (use-package sideline-flymake
  	:hook (flymake-mode . sideline-mode)
  	:custom
  	(sideline-flymake-display-mode 'line) ;; Show errors on the current line
  	(sideline-backends-right '(sideline-flymake)))
#+end_src

** Yasnippet
#+begin_src emacs-lisp
  (use-package yasnippet
    :hook (prog-mode . yas-minor-mode))

  (use-package yasnippet-snippets
    :after yasnippet)
#+end_src

** Envrc
Integrates direnv into Emacs. Automatically activates the correct environment
(venv, uv, Poetry, nix, etc.) when opening files in a project with a =.envrc= file.
Eglot and other tools pick up the right Python/executables automatically.
#+begin_src emacs-lisp
  (use-package envrc
    :hook (after-init . envrc-global-mode))
#+end_src


** Treesitter
#+begin_src emacs-lisp
  (setq treesit-language-source-alist
        '((bash "https://github.com/tree-sitter/tree-sitter-bash")
          (cmake "https://github.com/uyha/tree-sitter-cmake")
          (c "https://github.com/tree-sitter/tree-sitter-c")
          (cpp "https://github.com/tree-sitter/tree-sitter-cpp")
          (css "https://github.com/tree-sitter/tree-sitter-css")
          (elisp "https://github.com/Wilfred/tree-sitter-elisp")
          (go "https://github.com/tree-sitter/tree-sitter-go")
          (gomod "https://github.com/camdencheek/tree-sitter-go-mod")
          (html "https://github.com/tree-sitter/tree-sitter-html")
          (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
          (json "https://github.com/tree-sitter/tree-sitter-json")
  				(lua "https://github.com/tjdevries/tree-sitter-lua")
          (make "https://github.com/alemuller/tree-sitter-make")
          (markdown "https://github.com/ikatyang/tree-sitter-markdown")
          (python "https://github.com/tree-sitter/tree-sitter-python")
          (rust "https://github.com/tree-sitter/tree-sitter-rust")
          (toml "https://github.com/tree-sitter/tree-sitter-toml")
          (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
          (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
          (yaml "https://github.com/ikatyang/tree-sitter-yaml")
  				(heex "https://github.com/phoenixframework/tree-sitter-heex")
          (elixir "https://github.com/elixir-lang/tree-sitter-elixir")))

  (defun start/install-treesit-grammars ()
    "Install missing treesitter grammars"
    (interactive)
    (dolist (grammar treesit-language-source-alist)
      (let ((lang (car grammar)))
        (unless (treesit-language-available-p lang)
          (treesit-install-language-grammar lang)))))

  ;; Call this function to install missing grammars
  ;; (start/install-treesit-grammars)

  ;; Additional mode remappings not covered by defaults. Use add-to-list so we
  ;; don't clobber entries set elsewhere (Emacs or other packages).
  (dolist (remap '((yaml-mode . yaml-ts-mode)
                   (sh-mode . bash-ts-mode)
                   (c-mode . c-ts-mode)
                   (c++-mode . c++-ts-mode)
                   (css-mode . css-ts-mode)
                   (python-mode . python-ts-mode)
                   (mhtml-mode . html-ts-mode)
                   (javascript-mode . js-ts-mode)
                   (json-mode . json-ts-mode)
                   (lua-mode . lua-ts-mode)
                   (typescript-mode . typescript-ts-mode)
                   (conf-toml-mode . toml-ts-mode)
                   (elixir-mode . elixir-ts-mode)))
    (add-to-list 'major-mode-remap-alist remap))

  ;; Or if there is no built in mode
  (use-package cmake-ts-mode :ensure nil :mode ("CMakeLists\\.txt\\'" "\\.cmake\\'"))
  (use-package go-ts-mode :ensure nil :mode "\\.go\\'")
  (use-package go-mod-ts-mode :ensure nil :mode "\\.mod\\'")
  (use-package rust-ts-mode :ensure nil :mode "\\.rs\\'")
  (use-package tsx-ts-mode :ensure nil :mode "\\.tsx\\'")
#+end_src


** Language modes
It's not required for every language like C,C++,C#,Java,Javascript etc. to install language mode packages,
but for more specific languages it is necessary for syntax highlighting.
If you want to use TreeSitter, check out this [[https://www.masteringemacs.org/article/how-to-get-started-tree-sitter][website]] or try out [[https://github.com/renzmann/treesit-auto][Treesit-auto]].
Currently it's tedious to use Treesitter, because emacs has not yet fully migrated to it.

*** Lua mode
Example, how to setup a language mode (if you don't want it, feel free to delete it).
#+begin_src emacs-lisp
  (use-package lua-mode
    :mode "\\.lua\\'") ;; Only start in a lua file
#+end_src

*** Org Mode
Org mode is one of the things that emacs is loved for.
Once you've used it for a bit, you'll understand why people love it. Even reading about it can be inspiring!
For example, this document is effectively the source code and descriptions bound into the one document,
much like the literate programming ideas that Donald Knuth made famous.
#+begin_src emacs-lisp
  (use-package org
    :ensure nil
    :custom
    (org-edit-src-content-indentation 2) ;; Indent src block contents by 2 spaces.
    (org-return-follows-link t)          ;; RET follows links (TOC, URLs, etc.)

    :hook
    (org-mode . org-indent-mode))
#+end_src

*** Markdown mode

#+begin_src emacs-lisp
  (use-package markdown-mode
    :mode ("README\\.md\\'" . gfm-mode)
    :init (setq markdown-command "multimarkdown"))
#+end_src

*** Elixir mode
Setup Elixir mode using elixir-ts-mode and treesiter grammar
#+begin_src emacs-lisp
  (use-package elixir-ts-mode
    :hook
    (elixir-ts-mode . eglot-ensure)
    (heex-ts-mode   . eglot-ensure)
    (elixir-ts-mode . (lambda ()
                        (push '(">=" . ?\u2265) prettify-symbols-alist)  ;; ≥
                        (push '("<=" . ?\u2264) prettify-symbols-alist)  ;; ≤
                        (push '("!=" . ?\u2260) prettify-symbols-alist)  ;; ≠
                        (push '("==" . ?\u2A75) prettify-symbols-alist)  ;; ≝
                        (push '("=~" . ?\u2245) prettify-symbols-alist)  ;; ≈
                        (push '("<-" . ?\u2190) prettify-symbols-alist)  ;; ←
                        (push '("->" . ?\u2192) prettify-symbols-alist)  ;; →
                        (push '("|>" . ?\u25B7) prettify-symbols-alist)  ;; ▷
                        (prettify-symbols-mode 1)))
    (before-save . eglot-format))

#+end_src

**** Table of Contents
#+begin_src emacs-lisp
  (use-package toc-org
    :commands toc-org-enable
    :hook (org-mode . toc-org-mode))
#+end_src

**** Org Superstar
Prettify headings and plain lists in Org mode. Modern version of org-bullets.
#+begin_src emacs-lisp
  (use-package org-superstar
    :after org
    :hook (org-mode . org-superstar-mode))
#+end_src

**** Source Code Block Tag Expansion
Org-tempo is not a separate package but a module within org that can be enabled.
Org-tempo allows for '<s' followed by TAB to expand to a begin_src tag.
#+begin_src emacs-lisp
  (use-package org-tempo
    :ensure nil
    :after org
    :demand t)
#+end_src

** AI

*** Helpers

#+begin_src emacs-lisp
  (defun start/get-authinfo-secret (host user)
    "Retrieves and returns the secret from .authinfo given a host and user parameters.
  Returns nil if no matching entry is found."
    ;; THIS data should be store in ~/.authinfo in the following format:
  	;; machine api.mistral.ai login bearer password api-key-goes-here
    (let* ((auth-data (car (auth-source-search :max 1 :host host :user user)))
           (secret-function (plist-get auth-data :secret)))
      (and secret-function (funcall secret-function))))

  (defun start/api-mistral-get-bearer-token ()
    "Retrieves and returns the bearer token for Mistral API."
    (interactive)
  	(start/get-authinfo-secret "api.mistral.ai" "bearer"))

  (defun start/codestral-mistral-get-bearer-token ()
    "Retrieves and returns the bearer token for Mistral Codestrap API."
    (interactive)
  	(start/get-authinfo-secret "codestral.mistral.ai" "bearer"))
#+end_src

*** gptel
#+begin_src emacs-lisp
  (use-package gptel
    :config
    (let ((api-key (start/api-mistral-get-bearer-token)))
      (when api-key
        (setq gptel-model 'mistral-small
              gptel-backend
              (gptel-make-openai "MistralLeChat"
                :host "api.mistral.ai"
                :endpoint "/v1/chat/completions"
                :protocol "https"
                :key api-key
                :models '("mistral-small"))))))

#+end_src

*** Minuet
#+begin_src emacs-lisp
  (use-package minuet
    :bind
    (("M-i" . #'minuet-show-suggestion) ;; use overlay for completion
     ("C-c m i" . #'minuet-complete-with-minibuffer) ;; use minibuffer for completion
     ("C-c m c" . #'minuet-configure-provider)
     :map minuet-active-mode-map
     ;; These keymaps activate only when a minuet suggestion is displayed in the current buffer
     ("M-p" . #'minuet-previous-suggestion) ;; invoke completion or cycle to next completion
     ("M-n" . #'minuet-next-suggestion) ;; invoke completion or cycle to previous completion
     ("M-A" . #'minuet-accept-suggestion) ;; accept whole completion
     ;; Accept the first line of completion, or N lines with a numeric-prefix:
     ;; e.g. C-u 2 M-a will accepts 2 lines of completion.
     ("M-a" . #'minuet-accept-suggestion-line)
     ("M-e" . #'minuet-dismiss-suggestion))

    :init
    ;; if you want to enable auto suggestion.
    ;; Note that you can manually invoke completions without enable minuet-auto-suggestion-mode
    (add-hook 'prog-mode-hook #'minuet-auto-suggestion-mode)

    :config
    ;; Only configure if API key is available
    (let ((api-key (start/codestral-mistral-get-bearer-token)))
      (when api-key
        (setenv "CODESTRAL_API_KEY" api-key)
        ;; You can use M-x minuet-configure-provider to interactively configure provider and model
        (setq minuet-provider 'codestral)
        (minuet-set-optional-options minuet-codestral-options :stop ["\n\n"])
        (minuet-set-optional-options minuet-codestral-options :max_tokens 256)))
    )

#+end_src

*** agent-shell

#+begin_src emacs-lisp

  (use-package shell-maker
    :defer t)

  (use-package acp
    :vc (:url "https://github.com/xenodium/acp.el")
    :defer t)

  (use-package agent-shell
    :vc (:url "https://github.com/xenodium/agent-shell")
    :defer t)
#+end_src

** Terminal
*** Eat
Eat(Emulate A Terminal) is a terminal emulator within Emacs.
It's more portable and less overhead for users over like vterm or eshell.
We setup eat with eshell, if you want to use bash, zsh etc., check out their git [[https://codeberg.org/akib/emacs-eat][repository]] how to do it.
#+begin_src emacs-lisp
  (use-package eat
    :hook (eshell-load-hook . eat-eshell-mode))
#+end_src

* Version control

** Git
*** Magit
Complete text-based user interface to Git.
#+begin_src emacs-lisp
  (use-package magit
    :commands magit-status)
#+end_src

*** Diff-hl
Highlights uncommitted changes on the left side of the window (area also known as the "gutter"), allows you to jump between and revert them selectively.
#+begin_src emacs-lisp
  (use-package diff-hl
    :hook ((dired-mode         . diff-hl-dired-mode-unless-remote)
           (magit-pre-refresh  . diff-hl-magit-pre-refresh)
           (magit-post-refresh . diff-hl-magit-post-refresh))
    :init (global-diff-hl-mode))
#+end_src

* Completion

** Corfu
Enhances in-buffer completion with a small completion popup.
Corfu is a small package, which relies on the Emacs completion facilities and concentrates on providing a polished completion.
For more configuration options check out their [[https://github.com/minad/corfu][git repository]].
Notes:
- To enter Orderless field separator, use M-SPC.
#+begin_src emacs-lisp
  (use-package corfu
    :custom
    (corfu-cycle t)
    (corfu-auto t)
    (corfu-auto-prefix 2)
    (corfu-popupinfo-mode t)
    (corfu-popupinfo-delay 0.5)
    (corfu-separator ?\s)             ;; Orderless field separator, use M-SPC
    (corfu-preview-current nil)       ;; Don't insert completion without confirmation
    (completion-ignore-case t)
    (text-mode-ispell-word-completion nil)  ;; Use cape-dict instead (Emacs 30+)
    (tab-always-indent 'complete)
    :init
    (global-corfu-mode))

  (use-package nerd-icons-corfu
    :after corfu
    :init (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
#+end_src

** Cape
Provides Completion At Point Extensions which can be used in combination with Corfu, Company or the default completion UI.
Notes:
- The functions that are added later will be the first in the completion list.
- Take care when adding Capfs (Completion-at-point-functions) to the list since each of the Capfs adds a small runtime cost.
Read the [[https://github.com/minad/cape#configuration][configuration section]] in Cape's readme for more information.
#+begin_src emacs-lisp
  (use-package cape
    :after corfu
    :init
    ;; Functions added later appear earlier in the completion list.
    ;; Order from low to high priority — dabbrev (buffer-local words) is most
    ;; useful for programming, so it goes last.
    (add-to-list 'completion-at-point-functions #'cape-dict)
    (add-to-list 'completion-at-point-functions #'cape-file)
    (add-to-list 'completion-at-point-functions #'cape-elisp-block)
    (add-to-list 'completion-at-point-functions #'cape-keyword)
    (add-to-list 'completion-at-point-functions #'cape-dabbrev))
#+end_src

** Orderless
Completion style that divides the pattern into space-separated components, and matches candidates that match all of the components in any order.
Recomended for packages like vertico, corfu.
#+begin_src emacs-lisp
  (use-package orderless
    :custom
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src

** Vertico and Marginalia
- Vertico: Provides a performant and minimalistic vertical completion UI based on the default completion system.
- Savehist: Saves completion history.
- Marginalia: Adds extra metadata for completions in the margins (like descriptions).
- Nerd-icons-completion: Adds icons to completion candidates using the built in completion metadata functions.

We use this packages, because they use emacs native functions. Unlike Ivy or Helm.
One alternative is ivy and counsel, check out the [[https://github.com/MiniApollo/kickstart.emacs/wiki][project wiki]] for more inforomation.
#+begin_src emacs-lisp
  (use-package vertico
    :init
    (vertico-mode))

  (savehist-mode) ;; Enables save history mode

  (use-package marginalia
    :after vertico
    :init
    (marginalia-mode))

  (use-package nerd-icons-completion
    :after marginalia
    :config
    (nerd-icons-completion-mode)
    :hook
    (marginalia-mode . nerd-icons-completion-marginalia-setup))
#+end_src

** Consult
Provides search and navigation commands based on the Emacs completion function.
Check out their [[https://github.com/minad/consult][git repository]] for more awesome functions.
#+begin_src emacs-lisp
  (use-package consult-project-extra
    :after (consult project)
    :commands (consult-project-extra-find consult-project-extra-find-other-window))

  (use-package consult
    :hook (completion-list-mode . consult-preview-at-point-mode)
    :init
    (setq register-preview-delay 0.5
          register-preview-function #'consult-register-format)
    (advice-add #'register-preview :override #'consult-register-window)
    (setq xref-show-xrefs-function #'consult-xref
          xref-show-definitions-function #'consult-xref)
    ;; Include hidden files, exclude .git
    (setq consult-find-args "find . -not ( -path '*/.git/*' -prune )")
    (setq consult-fd-args "fd --hidden --exclude .git --full-path --color=never")
    :config
    ;; Use projectile's project root instead of project.el's
    (autoload 'projectile-project-root "projectile")
    (setq consult-project-function (lambda (_) (projectile-project-root)))
    ;; Enable live preview for the find commands (some default to manual M-.)
    (with-eval-after-load 'consult-project-extra
      (consult-customize
       consult-project-extra-find
       consult-project-extra-find-other-window
       consult-find
       consult-fd
       :preview-key 'any)))
#+end_src

** Embark
Contextual action menu for completion candidates and targets.
- =C-.= to act on any candidate in vertico, corfu, dired, etc.
- =C-,= as dwim (act on thing at point without prompt)
- From a =consult-ripgrep= result: embark-export to wgrep for mass editing
#+begin_src emacs-lisp
  (use-package embark
    :bind (("C-." . embark-act)
           ("C-," . embark-dwim)
           ("C-h B" . embark-bindings))
    :init
    (setq prefix-help-command #'embark-prefix-help-command))

  (use-package embark-consult
    :after (embark consult)
    :hook (embark-collect-mode . consult-preview-at-point-mode))
#+end_src

** Wgrep
Edit grep/ripgrep results as a regular buffer and save changes across files.
Use =C-c C-p= to enter wgrep mode from a =consult-ripgrep= result, =C-c C-c= to apply.
#+begin_src emacs-lisp
  (use-package wgrep
    :custom (wgrep-auto-save-buffer t))
#+end_src

** Helpful

#+begin_src emacs-lisp
  (use-package helpful
    ;; `helpful-callable' covers both functions and macros (drop-in for describe-function).
    :bind (("C-h f" . helpful-callable)
           ("C-h v" . helpful-variable)
           ("C-h k" . helpful-key)
           ("C-h x" . helpful-command)))
#+end_src

** Treemacs
Treemacs integration alongside projectile and dired
#+begin_src emacs-lisp
  (use-package treemacs
    :defer t
    :config
    (treemacs-follow-mode t)
    (treemacs-project-follow-mode t)
    (treemacs-filewatch-mode t)
    (treemacs-fringe-indicator-mode 'always)
    (when treemacs-python-executable
      (treemacs-git-commit-diff-mode t))
    (pcase (cons (not (null (executable-find "git")))
                 (not (null treemacs-python-executable)))
      (`(t . t) (treemacs-git-mode 'deferred))
      (`(t . _) (treemacs-git-mode 'simple)))
    :bind
    (:map global-map
          ("M-0"       . treemacs-select-window)
          ("C-x t 1"   . treemacs-delete-other-windows)
          ("C-x t t"   . treemacs)
          ("C-x t d"   . treemacs-select-directory)
          ("C-x t B"   . treemacs-bookmark)
          ("C-x t C-t" . treemacs-find-file)
          ("C-x t M-t" . treemacs-find-tag)))

  (use-package treemacs-nerd-icons
    :after (treemacs nerd-icons)
    :config
    (treemacs-load-theme "nerd-icons"))

  (use-package treemacs-projectile
    :after (treemacs projectile))

  (use-package treemacs-icons-dired
    :hook (dired-mode . treemacs-icons-dired-enable-once))

  (use-package treemacs-magit
    :after (treemacs magit))
#+end_src

** Diminish
This package implements hiding or abbreviation of the modeline displays (lighters) of minor-modes.
With this package installed, you can add ‘:diminish’ to any use-package block to hide that particular mode in the modeline.
#+begin_src emacs-lisp
  (use-package diminish)
#+end_src

** Rainbow Delimiters
Adds colors to brackets.
#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

** Which-Key
Which-key is a helper utility for keychords (which key to press).
#+begin_src emacs-lisp
  (use-package which-key
    :init
    (which-key-mode 1)
    :diminish
    :custom
    (which-key-side-window-location 'bottom)
    (which-key-sort-order #'which-key-key-order-alpha) ;; Same as default, except single characters are sorted alphabetically
    (which-key-sort-uppercase-first nil)
    (which-key-add-column-padding 1) ;; Number of spaces to add to the left of each column
    (which-key-min-display-lines 6)  ;; Increase the minimum lines to display, because the default is only 1
    (which-key-idle-delay 0.8)       ;; Set the time delay (in seconds) for the which-key popup to appear
    (which-key-max-description-length 25)
    (which-key-allow-imprecise-window-fit nil)) ;; Fixes which-key window slipping out in Emacs Daemon
#+end_src

** Ws-butler
#+begin_src emacs-lisp
  (use-package ws-butler
    :init (ws-butler-global-mode))
#+end_src

* Runtime Performance
Dial the GC threshold back down so that garbage collection happens more frequently but in less time.
We also increase Read Process Output Max so emacs can read more data.
#+begin_src emacs-lisp
  ;; Make gc pauses faster by decreasing the threshold.
  (setq gc-cons-threshold (* 2 1000 1000))
  ;; Increase the amount of data which Emacs reads from the process
  (setq read-process-output-max (* 1024 1024)) ;; 1mb
#+end_src
